### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by TsekNet** [ipcrm/registry_acl#14]
Hi,

Thanks for all your work putting this Puppet module together. We're interested in possibly leveraging this module internally at Windows @ Google. 

Looks like this repository is missing a LICENSE file, which is required before we can make use of this code. Can you add a LICENSE file (preferably Apache 2.0) when you have a moment?

Cheers,
Dan

**Comment by silug** [comment]
I don't _think_ that it is expected behavior for Puppet modules to ship with a `LICENSE` file for standard open-source licenses.  I'll look for clarification on that.

In the mean time, the license is clearly listed as `Apache-2.0` in [`metadata.json`](https://github.com/ipcrm/registry_acl/blob/master/metadata.json#L6).

**Comment by silug** [comment]
@TsekNet Added!  Thanks for the feedback.

**Comment by TsekNet** [comment]
@silug Thank you!
